### ISSUE TITLE
detector <object> focusable under Firefox?

### ISSUE THREAD

**Issue by teetotum** [wnr/element-resize-detector#35] opened 2015-12-22 12:44 UTC
The user *orbolanos* commented at [backalleycoder](http://www.backalleycoder.com/2013/03/18/cross-browser-event-based-element-resize-detection/) and stated that:
> It looks like the created object is focusable under Firefox.
> Adding the following code under addResizeListener fixes the issue.
> obj.setAttribute('tabindex', '-1');

As far as I understood you are using *backalleycoder*'s approach. Are you aware of this potential issue?

**Comment by wnr** [comment] 2015-12-22 15:05
Hi!

I am not aware of that. I'll have a look, and see if the fix needs to be added.

**Comment by wnr** [comment] 2016-05-15 15:13
I cannot reproduce the focusing issue in FireFox, so I'm closing this unless you can. Cheers :)

**Closed by wnr** 2016-05-15 15:13 UTC
