### ISSUE TITLE
MS Edge support?

### ISSUE THREAD

**Issue by RwwL** [wnr/element-resize-detector#33] opened 2015-12-21 12:11 UTC
I thought MS Edge was supported after seeing this script referenced in the comments on http://www.backalleycoder.com/2013/03/18/cross-browser-event-based-element-resize-detection/, but it appears to be having issues using either strategy. Minimal test cases: 

http://s.codepen.io/RwwL/debug/qbNamO (uses default strategy, not working in Edge with provided buttons or on window resize)

http://s.codepen.io/RwwL/debug/GoqNKd (uses scroll strategy, works in Edge on window resize but not after using the font size/padding buttons)

Maybe there's been a regression? Apologies if the mistake is in my usage or assumptions, of course.

Also possibly helpful info: working in CodePen's /pen/editors view, it appeared at first that the script wasn't working with any browser, but after checking the issues I think that may just be another occurrence of #31.

**Comment by marcj** [comment] 2015-12-21 12:20
Have you used current master version? We pulled in some fixed for new internet explorers lately

**Comment by wnr** [comment] 2015-12-21 13:39
Hi and thanks for the bug report.

I'll have a look and get back to you when I have more information :)

**Comment by RwwL** [comment] 2015-12-21 13:55
@marcj Yep, copied https://raw.githubusercontent.com/wnr/element-resize-detector/master/dist/element-resize-detector.min.js straight into my CodePen.

**Comment by wnr** [comment] 2015-12-21 14:00
There seems to be an issue with padding of elements that are being listened for resize events with the scroll strategy (I haven't tested the object strategy in Edge yet). While waiting, one could wrap the `container` div with another container so that the listening container does not have any padding. This is probably an issue with how width/height is being measured (not taking padding into account). I think this should be fairly easy to fix.

**Comment by marcj** [comment] 2015-12-21 14:06
Oh, ooops, sorry guys, I though this issue is in another repo. So please ignore my post. :)

**Comment by wnr** [comment] 2015-12-21 14:17
No problems :)

**Comment by wnr** [comment] 2015-12-21 14:18
@RwwL I have now confirmed that the container fix I suggested works in Edge now. I admit it is now the prettiest, but it is at least a fix while waiting.

**Comment by RwwL** [comment] 2015-12-21 14:22
Thanks, @wnr — adding a container would only help pick up padding changes, not font-size or other properties, correct?

**Comment by wnr** [comment] 2015-12-21 14:26
The added container will pick up any changes made to the size of the `.container` element. If the font size is changed without affecting the `.container` element, erd is not supposed to emit an event. In your example, there will be a resize event when changing the font size as the height of the `.container` element is changed.

**Comment by RwwL** [comment] 2015-12-21 14:31
Thanks! Unfortunately my use case is one where adding another container is probably not a viable option. I'll just keep watching for any eventual updates.

**Comment by wnr** [comment] 2015-12-21 14:33
Okay too bad. I can try to ping you when a fix has been released :)

**Comment by wnr** [comment] 2016-02-13 23:29
This is now fixed in the 1.1.0 release

**Closed** 2016-02-21 09:23 UTC
