### ISSUE TITLE
Uncaught TypeError: Cannot read property 'width' of undefined

### ISSUE THREAD

**Issue by Poordeveloper** [wnr/element-resize-detector#94] opened 2018-05-08 16:27 UTC
"version": "1.1.14"

scroll.js?1887:570 Uncaught TypeError: Cannot read property 'width' of undefined
    at registerListenersAndPositionElements (scroll.js?1887:570)
    at Object.process (batch-processor.js?e841:124)
    at processBatch (batch-processor.js?e841:37)

**Comment by Poordeveloper** [comment] 2018-05-09 07:33
It happened when I resize the browser window. I do not use element-resize-detector directly, but I am using react-sizeme which is using element-resize-detector. As a wordaround, I put below into package.json
`sed -i \"s/var style = getState(element).style;/var style = getState(element).style ;if(!style)return;/g\" node_modules/element-resize-detector/src/detection-strategy/scroll.js`

**Comment by Poordeveloper** [comment] 2018-05-09 07:37
It only happen when I resize the browser window more than once.

**Comment by Poordeveloper** [comment] 2018-05-09 07:38
I only tested on google chrome.

**Comment by Poordeveloper** [comment] 2018-05-09 07:39
this pull request https://github.com/wnr/element-resize-detector/pull/93 is very similar to this bug. Though the pull request does not fix this bug.

**Comment by wnr** [comment] 2018-05-09 07:48
Okay, thank you. Could you perhaps provide a minimal jsbin example for my to try? Have you opened an issue in react-sizeme as well?

**Comment by Poordeveloper** [comment] 2018-05-09 07:53
I will open an issue on react-sizeme.

**Comment by wnr** [comment] 2018-05-14 07:58
I'll close this for now as I think that the issue is outside of this library. I'll reopen if your analysis points in the opposite direction.

**Closed by wnr** 2018-05-14 07:58 UTC
