### ISSUE TITLE
Uncaught TypeError: Cannot read property 'container' of undefined

### ISSUE THREAD

**Issue by Almenit** [wnr/element-resize-detector#59] opened 2016-08-23 07:53 UTC
I have an error when quickly adding and removing an element from DOM:
```javascript
Uncaught TypeError: Cannot read property 'container' of undefined
```
Happens in Chrome, can't reproduce it in IE 11 or Firefox. 
We use React. 

Stacktrace
```javascript
getExpandElement
getExpandChildElement
updateChildSizes
performUpdateChildSizes
process
processBatch
```

I can se that the the error happens after the element is uninstalled.

**Comment by wnr** [comment] 2016-08-23 08:04
Hi, and thanks for the report!

That sounds like an issue similar to what was fixed in version 1.1.7, are you using that version?

If you do use 1.1.7, could you provide a minimal case reproducing the issue?

Thanks

**Comment by Almenit** [comment] 2016-08-23 08:19
Yes we do use 1.1.7. 
If I look at your code I can't see any guard on performUpdateChildSizes. And since this is async. I can see that my case can happen, even if you check it i.e. onExpandScroll

**Comment by wnr** [comment] 2016-08-23 09:38
> If I look at your code I can't see any guard on performUpdateChildSizes.

There should be a guard:
https://github.com/wnr/element-resize-detector/blob/master/src/detection-strategy/scroll.js#L419

It also seems to be present in the dist files. Isn't it present in your files?

**Comment by Almenit** [comment] 2016-08-23 09:51
Great. Sorry. That file was not updated for some strange reason. Now it works and I can see the guard.

**Comment by wnr** [comment] 2016-08-23 09:54
Okay, great! :)

**Closed by wnr** 2016-08-23 09:54 UTC
